import type { Prisma } from '../generated/prisma/client';
import { addDays, todayInTimezone } from '../utils/date';
import { env } from '../utils/env';
import { prisma } from '../utils/prisma';
import { getOccurrenceDates } from '../utils/recurrence';

// Safety cap for a single run (e.g. a weekly rule started years ago).
// The remaining occurrences are generated by the next runs.
const MAX_OCCURRENCES_PER_RUN = 366;

const templateSelect = {
  id: true,
  userId: true,
  accountId: true,
  categoryId: true,
  type: true,
  amount: true,
  description: true,
  notes: true,
  frequency: true,
  day: true,
  startDate: true,
  endDate: true,
  lastRunDate: true,
} satisfies Prisma.RecurringTransactionSelect;

type Template = Prisma.RecurringTransactionGetPayload<{ select: typeof templateSelect }>;

// Generates the occurrences of one template due until `today`.
//
// Idempotency and concurrency:
// 1. last_run_date is advanced with a conditional UPDATE (WHERE last_run_date =
//    the value we read) inside a transaction. The UPDATE locks the row, so a
//    concurrent run waits, then matches 0 rows and generates nothing.
// 2. The unique index (recurring_transaction_id, date) plus skipDuplicates is a
//    second barrier against duplicates.
// 3. Because generation always starts after last_run_date, an occurrence the
//    user deleted on purpose is never recreated.
async function generateForTemplate(template: Template, today: Date): Promise<number> {
  const from = template.lastRunDate ? addDays(template.lastRunDate, 1) : template.startDate;
  const until = template.endDate && template.endDate < today ? template.endDate : today;

  if (from > until) return 0;

  let dates = getOccurrenceDates(template, from, until);
  let runUntil = until;

  if (dates.length > MAX_OCCURRENCES_PER_RUN) {
    dates = dates.slice(0, MAX_OCCURRENCES_PER_RUN);
    runUntil = dates[dates.length - 1] ?? until;
  }

  return prisma.$transaction(async (tx) => {
    const claimed = await tx.recurringTransaction.updateMany({
      where: { id: template.id, lastRunDate: template.lastRunDate },
      data: { lastRunDate: runUntil },
    });

    // Another run already processed this template
    if (claimed.count === 0 || dates.length === 0) return 0;

    const { count } = await tx.transaction.createMany({
      data: dates.map((date) => ({
        userId: template.userId,
        accountId: template.accountId,
        categoryId: template.categoryId,
        recurringTransactionId: template.id,
        type: template.type,
        amount: template.amount,
        description: template.description,
        notes: template.notes,
        date,
      })),
      skipDuplicates: true,
    });

    return count;
  });
}

interface GenerateOptions {
  userId?: string;
  templateId?: string;
  today?: Date;
}

export async function generateDueRecurringTransactions(options: GenerateOptions = {}) {
  const today = options.today ?? todayInTimezone(env.APP_TIMEZONE);

  const templates = await prisma.recurringTransaction.findMany({
    where: {
      ...(options.userId && { userId: options.userId }),
      ...(options.templateId && { id: options.templateId }),
      active: true,
      // Archived accounts receive no new movements; resumes if unarchived
      account: { archived: false },
      startDate: { lte: today },
      OR: [{ lastRunDate: null }, { lastRunDate: { lt: today } }],
    },
    select: templateSelect,
  });

  let created = 0;

  for (const template of templates) {
    created += await generateForTemplate(template, today);
  }

  return { templates: templates.length, created };
}
