-- CreateEnum
CREATE TYPE "TransactionSource" AS ENUM ('MANUAL', 'IMPORT', 'RECURRING');

-- AlterTable
ALTER TABLE "transactions" ADD COLUMN     "import_file_name" VARCHAR(255),
ADD COLUMN     "source" "TransactionSource" NOT NULL DEFAULT 'MANUAL';

-- Backfill: occurrences generated by a recurring template. Imported rows
-- created before this migration cannot be told apart and stay MANUAL.
UPDATE "transactions" SET "source" = 'RECURRING' WHERE "recurring_transaction_id" IS NOT NULL;
