import {
  Baby,
  BookOpen,
  Briefcase,
  Car,
  CircleEllipsis,
  CirclePlus,
  Coffee,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Lock,
  type LucideIcon,
  Music,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Target,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Zap,
} from 'lucide-react';

// Icons are stored by their lucide name. Only this curated set is bundled
// (importing every lucide icon would add hundreds of kilobytes); it is also
// the list offered when creating a category.
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  laptop: Laptop,
  'trending-up': TrendingUp,
  gift: Gift,
  'circle-plus': CirclePlus,
  utensils: Utensils,
  'shopping-cart': ShoppingCart,
  house: House,
  receipt: Receipt,
  car: Car,
  'heart-pulse': HeartPulse,
  'graduation-cap': GraduationCap,
  'gamepad-2': Gamepad2,
  repeat: Repeat,
  'shopping-bag': ShoppingBag,
  plane: Plane,
  'paw-print': PawPrint,
  landmark: Landmark,
  'circle-ellipsis': CircleEllipsis,
  coffee: Coffee,
  fuel: Fuel,
  smartphone: Smartphone,
  wifi: Wifi,
  zap: Zap,
  shirt: Shirt,
  baby: Baby,
  dumbbell: Dumbbell,
  film: Film,
  music: Music,
  'book-open': BookOpen,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  target: Target,
  shield: Shield,
  lock: Lock,
};

export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICONS[name] ?? CircleEllipsis;
}
